services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_USER=${DB_User}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: skillcup
      MYSQL_USER: skillcup
      MYSQL_PASSWORD: skillcup
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
