"""create players and searches table

Revision ID: fc4096c62ec2
Revises: 
Create Date: 2026-07-19 11:44:42.657048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc4096c62ec2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('referral_code', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('twitch_username', sa.String(length=255), nullable=True),
    sa.Column('youtube_username', sa.String(length=255), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=True),
    sa.Column('favourite_player', sa.String(length=255), nullable=True),
    sa.Column('favourite_team', sa.String(length=255), nullable=True),
    sa.Column('sheba', sa.String(length=255), nullable=True),
    sa.Column('ea_id', sa.String(length=255), nullable=True),
    sa.Column('deactivation_reason', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('is_fake', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_player_username', 'players', ['username'], unique=False)
    op.create_index('ix_search_id_status', 'players', ['id', 'status'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('xp_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_player_id', 'searches', ['player_id'], unique=False)
    op.create_index('ix_search_player_id_status', 'searches', ['player_id', 'status'], unique=False)
    # ### end Alembic commands ###
    op.execute("ALTER TABLE players MODIFY updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP")
    op.execute("ALTER TABLE searches MODIFY updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_player_id_status', table_name='searches')
    op.drop_index('ix_search_player_id', table_name='searches')
    op.drop_table('searches')
    op.drop_index('ix_search_id_status', table_name='players')
    op.drop_index('ix_player_username', table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
